#!/usr/bin/env python
# -*- coding: utf-8 -*-
# --------------------------------
# Copyright (c) 2015 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

from __future__ import print_function

from canopsis.common.utils import lookup
import pprint
import plac
import sys


def main(manager, method, args):
    pp = pprint.PrettyPrinter(indent=2)

    cls = lookup(manager)
    mgr = cls()

    ret = plac.call(getattr(mgr, method), args)
    pp.pprint(ret)


if __name__ == '__main__':
    if len(sys.argv) < 3 or sys.argv[1] in ['-h', '--help']:
        print(
            "Usage:", sys.argv[0], "manager method [args...]",
            file=sys.stderr
        )
        sys.exit(1)

    main(sys.argv[1], sys.argv[2], sys.argv[3:])
