#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
# --------------------------------
# Copyright (c) 2015 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

from canopsis.engines.core import Engine

from argparse import ArgumentParser
from multiprocessing import Process
from time import sleep


if __name__ == '__main__':
    parser = ArgumentParser(description='Engine launcher')
    parser.add_argument(
        '-n', '--name',
        nargs=1,
        help='Engine\'s name',
        required=True
    )
    parser.add_argument(
        '-w', '--worker',
        nargs=1,
        type=int,
        help='Engine worker instance'
    )
    parser.add_argument(
        '-l', '--log',
        nargs=1,
        help='Engine \'s logging level'
    )

    args = parser.parse_args()

    name = args.name[0]
    worker = None if not args.worker else args.worker[0]
    loglevel = None if not args.log else args.log[0].upper()

    engine = Engine.load(name=name, worker=worker, log_lvl=loglevel)

    p = Process(target=engine.run)
    p.start()

    try:
        while True:
            sleep(1)

    except KeyboardInterrupt:
        engine.stop()

    p.join()
